alertmanager:
  enabled: true
server:
  enabled: true
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false

serverFiles:
  alerting_rules.yml:
    groups:
      - name: myalerts
        rules:
          # Sets up alert for any assertion fails
          - alert: PostmanAssertionsFailed
            expr: postman_stats_assertions_failed > 0
            for: 1m
            annotations:
              summary: Postman collection run, one or more assertions failed
          - alert: PostmanRequestsFailed
            expr: postman_stats_requests_failed > 0
            for: 1m
            annotations:
              summary: Postman collection run, one or more requests failed

# Sets up alertmanager to use GMail for email alerts
alertmanagerFiles:
  alertmanager.yml:
    global: {}
    receivers:
      - name: email-me
        email_configs:
          - to: __CHANGE_ME__@gmail.com
            from: __CHANGE_ME__@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: '__CHANGE_ME__@gmail.com'
            auth_identity: '__CHANGE_ME__@gmail.com'
            auth_password: '__CHANGE_ME__'
    route:
      group_by: [Alertname]
      receiver: email-me
